openvpn:

    - auth: SHA1
    - cipher: AES-256-CBC
    - keepalive: "10 30"
    - tls-cipher: DHE-RSA-AES128-SHA
    - tun-ipv6: true
    - dev: tun
    - sndbuf: 0
    - rcvbuf: 0
    - nobind: true
    - persist-key: true
    - key-direction: 1
    - verb: 3

locations:

    - Amsterdam:
        - name: Amsterdam
        - country_code: NL
        - hemisphere: N
        - timezone: -1


gateways:

    - pt.demo.bitmask.net:
        - host: pt.demo.bitmask.net
        - ip_address: 37.218.247.60
        - location: Amsterdam
        - transports:
            - [ "openvpn", "tcp", "443"]
            - [ "obfs4", "tcp", "23042"]
